Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LogTime yes
StreamMaxLength 100M
MaxFileSize 100M
MaxScanSize 200M
MaxRecursion 10
MaxFiles 1000
MaxScanTime 120000
AlertExceedsMax yes
AlertEncrypted yes
ConcurrentDatabaseReload no
